import React, { useState, useRef, useCallback } from 'react';
import { VOICES, API_SAMPLE_RATE, API_NUM_CHANNELS } from './constants';
import { VoiceSelector } from './components/VoiceSelector';
import { generateSpeech } from './services/geminiService';
import { decode, decodeAudioData, createWavBlob } from './utils/audioUtils';
import { PlayIcon, StopIcon, DownloadIcon, LoaderIcon, KeyIcon } from './components/icons';
import { ApiKeyModal } from './components/ApiKeyModal';

export default function App() {
  const [apiKey, setApiKey] = useState<string | null>(() => {
    try {
      return localStorage.getItem('gemini-api-key');
    } catch (e) {
      console.error('Failed to access localStorage:', e);
      return null;
    }
  });
  const [text, setText] = useState('Hello! I am a friendly AI voice generated by Gemini. How are you doing today?');
  const [selectedVoice, setSelectedVoice] = useState(VOICES[0].id);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [audioData, setAudioData] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [speed, setSpeed] = useState(1.0);
  const [pitch, setPitch] = useState('medium'); // 'low', 'medium', 'high'

  const audioContextRef = useRef<AudioContext | null>(null);
  const audioSourceRef = useRef<AudioBufferSourceNode | null>(null);
  const audioBufferRef = useRef<AudioBuffer | null>(null);

  const handleApiKeySubmit = (key: string) => {
    try {
      localStorage.setItem('gemini-api-key', key);
      setApiKey(key);
      setError(null);
    } catch (e) {
      console.error('Failed to save API key to localStorage:', e);
      setError('Could not save API key. Please ensure localStorage is enabled in your browser.');
    }
  };

  const handleClearApiKey = useCallback(() => {
    try {
        localStorage.removeItem('gemini-api-key');
    } catch (e) {
        console.error('Failed to remove API key from localStorage:', e);
    }
    setApiKey(null);
    setError(null);
    setAudioData(null);
    audioBufferRef.current = null;
    if (isPlaying) {
        audioSourceRef.current?.stop();
        setIsPlaying(false);
    }
  }, [isPlaying]);

  const handleSelectVoice = (voiceId: string) => {
    setSelectedVoice(voiceId);
    if (voiceId === 'robot') {
      setPitch('low');
    }
  };

  const handleGenerateSpeech = useCallback(async () => {
    if (!apiKey) {
      setError('Please provide your Gemini API key.');
      return;
    }
    if (!text.trim()) {
      setError('Please enter some text to generate speech.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setAudioData(null);
    audioBufferRef.current = null;

    if (isPlaying) {
        audioSourceRef.current?.stop();
        setIsPlaying(false);
    }

    try {
      const voiceForApi = selectedVoice === 'robot' ? 'zubenelgenubi' : selectedVoice;
      const generatedAudio = await generateSpeech(text, voiceForApi, apiKey);
      setAudioData(generatedAudio);
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : 'An unexpected error occurred.';
      setError(errorMessage);
      if (errorMessage.toLowerCase().includes('api key')) {
        handleClearApiKey();
      }
    } finally {
      setIsLoading(false);
    }
  }, [apiKey, text, selectedVoice, isPlaying, handleClearApiKey]);

  const handlePlayStopAudio = useCallback(async () => {
    if (isPlaying) {
      audioSourceRef.current?.stop();
      return;
    }

    if (!audioData) return;

    try {
      if (!audioContextRef.current) {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({
          sampleRate: API_SAMPLE_RATE,
        });
      }
      const ctx = audioContextRef.current;
      if (ctx.state === 'suspended') await ctx.resume();

      if (!audioBufferRef.current) {
        const decodedBytes = decode(audioData);
        audioBufferRef.current = await decodeAudioData(decodedBytes, ctx, API_SAMPLE_RATE, API_NUM_CHANNELS);
      }
      
      const source = ctx.createBufferSource();
      source.buffer = audioBufferRef.current;
      
      source.playbackRate.value = speed;
      const pitchValue = { low: -400, medium: 0, high: 400 }[pitch] || 0;
      source.detune.value = pitchValue;

      source.connect(ctx.destination);
      source.onended = () => {
        setIsPlaying(false);
        audioSourceRef.current = null;
      };
      source.start(0);
      audioSourceRef.current = source;
      setIsPlaying(true);
    } catch (e) {
      console.error("Error playing audio:", e);
      setError("Failed to play audio. The data might be corrupted.");
      setIsPlaying(false);
    }
  }, [audioData, isPlaying, speed, pitch]);
  
  const handleDownload = useCallback(() => {
    if (!audioBufferRef.current) {
        if (!audioData) {
            setError("No audio to download.");
            return;
        }
         if (!audioContextRef.current) {
            audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({
                sampleRate: API_SAMPLE_RATE,
            });
         }
        const ctx = audioContextRef.current;
        const decodedBytes = decode(audioData);
        decodeAudioData(decodedBytes, ctx, API_SAMPLE_RATE, API_NUM_CHANNELS).then(buffer => {
            audioBufferRef.current = buffer;
            downloadBlob(buffer);
        });
    } else {
        downloadBlob(audioBufferRef.current);
    }
  }, [audioData, selectedVoice]);

  const downloadBlob = (buffer: AudioBuffer) => {
    const wavBlob = createWavBlob(buffer);
    const url = URL.createObjectURL(wavBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gemini-speech-${selectedVoice.toLowerCase()}.wav`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const isUiDisabled = isLoading || !apiKey;

  return (
    <>
      {!apiKey && <ApiKeyModal onApiKeySubmit={handleApiKeySubmit} />}
      <div className="min-h-screen bg-slate-900 text-slate-200 flex flex-col items-center justify-center p-4 font-sans">
        <div className="w-full max-w-2xl mx-auto">
          <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl shadow-2xl p-6 md:p-8 space-y-6 border border-slate-700">
            <header className="text-center relative">
              <h1 className="text-3xl sm:text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">
                AI Voice Generator
              </h1>
              <p className="text-slate-400 mt-2">
                Powered by Google Gemini Text-to-Speech
              </p>
               {apiKey && (
                 <div className="absolute top-0 right-0">
                    <button
                        onClick={handleClearApiKey}
                        className="flex items-center text-xs text-slate-400 hover:text-indigo-400 transition-colors duration-200 bg-slate-700/50 hover:bg-slate-700 px-2 py-1 rounded-md"
                        title="Change API Key"
                    >
                        <KeyIcon className="w-3 h-3 mr-1.5" />
                        Change Key
                    </button>
                 </div>
              )}
            </header>

            <div className="space-y-4">
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Enter text to generate speech..."
                className="w-full h-36 p-4 bg-slate-900/70 border-2 border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition duration-200 resize-none disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isUiDisabled}
              />
              <VoiceSelector
                voices={VOICES}
                selectedVoice={selectedVoice}
                onSelectVoice={handleSelectVoice}
                disabled={isUiDisabled}
                isPlaying={isPlaying}
                speed={speed}
                onSpeedChange={setSpeed}
                pitch={pitch}
                onPitchChange={setPitch}
              />
            </div>

            {error && <div className="bg-red-500/20 text-red-300 border border-red-500/30 p-3 rounded-lg text-sm">{error}</div>}

            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={handleGenerateSpeech}
                disabled={isUiDisabled}
                className="flex-1 inline-flex items-center justify-center px-6 py-3 font-semibold text-white bg-indigo-600 rounded-lg shadow-lg hover:bg-indigo-700 disabled:bg-slate-600 disabled:cursor-not-allowed transition-all duration-200 transform hover:scale-105 disabled:scale-100"
              >
                {isLoading ? (
                  <>
                    <LoaderIcon className="w-5 h-5 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  'Generate Speech'
                )}
              </button>
              <div className="flex gap-4">
                <button
                  onClick={handlePlayStopAudio}
                  disabled={!audioData || isUiDisabled}
                  className="flex-1 w-full sm:w-auto inline-flex items-center justify-center px-6 py-3 font-semibold bg-slate-700 text-slate-200 rounded-lg hover:bg-slate-600 disabled:bg-slate-800 disabled:text-slate-500 disabled:cursor-not-allowed transition-colors duration-200"
                  aria-label={isPlaying ? 'Stop audio' : 'Play audio'}
                >
                  {isPlaying ? <StopIcon className="w-6 h-6" /> : <PlayIcon className="w-6 h-6" />}
                </button>
                <button
                  onClick={handleDownload}
                  disabled={!audioData || isUiDisabled}
                  className="flex-1 w-full sm:w-auto inline-flex items-center justify-center px-6 py-3 font-semibold bg-slate-700 text-slate-200 rounded-lg hover:bg-slate-600 disabled:bg-slate-800 disabled:text-slate-500 disabled:cursor-not-allowed transition-colors duration-200"
                  aria-label="Download audio"
                >
                  <DownloadIcon className="w-6 h-6" />
                </button>
              </div>
            </div>
          </div>
          <footer className="text-center mt-6 text-xs text-slate-500">
              <p>Generated audio is for personal use. Ensure compliance with Google's terms of service.</p>
          </footer>
        </div>
      </div>
    </>
  );
}